### ISSUE TITLE
For `lpad webgui`, try another port if the first one is in use

### ISSUE THREAD

**Issue by jakirkham** [materialsproject/fireworks#107]
Port 5000 is a common one to use. There should be a more graceful fallback than just crashing (e.g. bump the port number and try again).

     * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
    Process Process-1:
    Traceback (most recent call last):
      File "/zopt/conda/envs/nanshenv/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/flask/app.py", line 772, in run
        run_simple(host, port, self, **options)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/werkzeug/serving.py", line 625, in run_simple
        inner()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/werkzeug/serving.py", line 603, in inner
        passthrough_errors, ssl_context).serve_forever()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/werkzeug/serving.py", line 512, in make_server
        passthrough_errors, ssl_context)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/werkzeug/serving.py", line 440, in __init__
        HTTPServer.__init__(self, (host, int(port)), handler)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/SocketServer.py", line 420, in __init__
        self.server_bind()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
        SocketServer.TCPServer.server_bind(self)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/SocketServer.py", line 434, in server_bind
        self.socket.bind(self.server_address)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/socket.py", line 228, in meth
        return getattr(self._sock,name)(*args)
    error: [Errno 48] Address already in use

**Comment by computron** [comment]
I will try to do this at some point - note that there is already a --port option that lets you switch the port, e.g. "lpad webgui --port 1111"

**Comment by jakirkham** [comment]
Understood and that is good to have for sure. Honestly, I was debating whether this issue shouldn't be raised with `flask` as they allow this default to be picked and maybe they should be doing something smarter.

**Comment by computron** [comment]
Based on another user comment I have added the ability to set a WEBSERVER_PORT argument in the FW_config.yaml, which lets you set the default port however you'd like. This solution allows you to set different default ports for dev/prod/etc. which is useful for some, and also avoids the automatically searching for a port solution which is in my opinion a bit random and inconsistent.

The change is already committed and will be released on PyPI soon. I'm closing this for now, but let me know if you still see problems.
