### ISSUE TITLE
AttributeError with command qlaunch

### ISSUE THREAD

**Issue by specter119** [materialsproject/fireworks#148]
python:  2.7.11
fireworks: 1.2.9 (develop model)

for the command `qlaunch -r rapidfire --nlaunches infinite -m 1 --sleep 100 -b 10000`
I got :
```
my environment
usage: qlaunch [-h] [-rh [REMOTE_HOST [REMOTE_HOST ...]]]
               [-rc REMOTE_CONFIG_DIR [REMOTE_CONFIG_DIR ...]]
               [-ru REMOTE_USER] [-rp REMOTE_PASSWORD] [-rs] [-d DAEMON]
               [--launch_dir LAUNCH_DIR] [--logdir LOGDIR] [--loglvl LOGLVL]
               [-s] [-r] [-l LAUNCHPAD_FILE] [-w FWORKER_FILE]
               [-q QUEUEADAPTER_FILE] [-c CONFIG_DIR]
               {singleshot,rapidfire} ...
qlaunch: error: unrecognized arguments: -r rapidfire
```

then I removed -r rapidfire, then I typed `qlaunch --nlaunches infinite -m 1 --sleep 100 -b 10000`
I got :
```
my environment
Traceback (most recent call last):
  File "/lustre/home/umjzhh-1/kl_me2/virtenv_kl_me2/bin/qlaunch", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/scripts/qlaunch", line 6, in <module>
    qlaunch()
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/scripts/qlaunch_run.py", line 173, in qlaunch
    do_launch(args)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/scripts/qlaunch_run.py", line 52, in do_launch
    reserve=args.reserve, strm_lvl=args.loglvl, timeout=args.timeout)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/queue/queue_launcher.py", line 174, in rapidfire
    start_time = datetime.now()
AttributeError: 'module' object has no attribute 'now'
```
Now I found 2 solutions:
in `fireworks/queue/queue_launcher.py`
1. replace `import datetime` with `from datetime import datetime`
2. replace `datetime.now()` with `datetime.datetime.now()`

**Comment by dwinston** [comment]
Thanks. Using solution 1 to be consistent with `fireworks/core/rocket_launcher.py` usage.
