### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'as_dict'

### ISSUE THREAD

**Issue by specter119** [materialsproject/fireworks#159]
* FireWorks version: master
* OS version: Red Hat Enterprise Linux Server release 6.3 (Santiago)

## Error command

`lpad get_fws` `lpad rerun_fws -s RESERVED` and similar commands for fireworks

## Error message

error message of `lpad get_fws`
```sh
kl_me2 environment
/lustre/home/umjzhh-1/kl_me2/codes/pymatgen/pymatgen/io/vasp/sets_deprecated.py:460: DeprecationWarning: __init__ is deprecated
All vasp input sets have been replaced by equivalents pymatgen.io.sets. Will be removed in pmg 4.0.
  return DictVaspInputSet(name, loadfn(filename), **kwargs)
Traceback (most recent call last):
  File "/lustre/home/umjzhh-1/kl_me2/virtenv_kl_me2/bin/lpad", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/scripts/lpad", line 6, in <module>
    lpad()
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/scripts/lpad_run.py", line 863, in lpad
    args.func(args)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/scripts/lpad_run.py", line 208, in get_fws
    fw = lp.get_fw_by_id(id)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/launchpad.py", line 316, in get_fw_by_id
    return Firework.from_dict(self.get_fw_dict_by_id(fw_id))
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 148, in _decorator
    m_dict = func(self, *new_args, **kwargs)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/firework.py", line 325, in from_dict
    state, created_on, fw_id, updated_on=updated_on)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/firework.py", line 218, in __init__
    tasks]  # put tasks in a special location of the spec
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 161, in _decorator
    m_dict = func(self, *args, **kwargs)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 133, in _decorator
    m_dict = recursive_dict(m_dict)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 76, in recursive_dict
    return {recursive_dict(k, preserve_unicode): recursive_dict(v, preserve_unicode) for k, v in obj.items()}
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 76, in <dictcomp>
    return {recursive_dict(k, preserve_unicode): recursive_dict(v, preserve_unicode) for k, v in obj.items()}
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 79, in recursive_dict
    return [recursive_dict(v, preserve_unicode) for v in obj]
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 70, in recursive_dict
    return recursive_dict(obj.as_dict(), preserve_unicode)
  File "/lustre/home/umjzhh-1/kl_me2/codes/custodian/custodian/vasp/jobs.py", line 347, in as_dict
    default_vasp_input_set=self.default_vis.as_dict(),
AttributeError: 'dict' object has no attribute 'as_dict'
```

error message of `lpad rerun_fws -s RESERVED`

```sh
l_me2 environment
Are you sure? This will modify 40 entries. (Y/N)Y
/lustre/home/umjzhh-1/kl_me2/codes/pymatgen/pymatgen/io/vasp/sets_deprecated.py:460: DeprecationWarning: __init__ is deprecated
All vasp input sets have been replaced by equivalents pymatgen.io.sets. Will be removed in pmg 4.0.
  return DictVaspInputSet(name, loadfn(filename), **kwargs)
2016-06-03 20:31:30,242 DEBUG Processed fw_id: ...
...
2016-06-03 20:31:31,194 INFO Also rerunning duplicate fw_id: 11131
2016-06-03 20:31:31,233 DEBUG Processed fw_id: 3940
2016-06-03 20:31:31,276 INFO Also rerunning duplicate fw_id: 11110
2016-06-03 20:31:31,323 DEBUG Processed fw_id: 3947
2016-06-03 20:31:31,375 INFO Also rerunning duplicate fw_id: 11103
2016-06-03 20:31:31,416 DEBUG Processed fw_id: 3968
2016-06-03 20:31:30,242 DEBUG Processed fw_id: ...
Traceback (most recent call last):
  File "/lustre/home/umjzhh-1/kl_me2/virtenv_kl_me2/bin/lpad", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/scripts/lpad", line 6, in <module>
    lpad()
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/scripts/lpad_run.py", line 863, in lpad
    args.func(args)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/scripts/lpad_run.py", line 387, in rerun_fws
    lp.rerun_fw(int(f))
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/launchpad.py", line 966, in rerun_fw
    updated_ids = wf.rerun_fw(fw_id)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/firework.py", line 836, in rerun_fw
    self.rerun_fw(child_id, updated_ids))
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/firework.py", line 830, in rerun_fw
    m_fw._rerun()
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/launchpad.py", line 1219, in _rerun
    self.full_fw._rerun()
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/launchpad.py", line 1309, in full_fw
    self._get_launch_data(launch_field)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/launchpad.py", line 1320, in _get_launch_data
    fw = self.partial_fw  # assure stage 1
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/launchpad.py", line 1302, in partial_fw
    self._fw = Firework.from_dict(data)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 148, in _decorator
    m_dict = func(self, *new_args, **kwargs)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/firework.py", line 325, in from_dict
    state, created_on, fw_id, updated_on=updated_on)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/firework.py", line 218, in __init__
    tasks]  # put tasks in a special location of the spec
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 161, in _decorator
    m_dict = func(self, *args, **kwargs)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 133, in _decorator
    m_dict = recursive_dict(m_dict)
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 76, in recursive_dict
    return {recursive_dict(k, preserve_unicode): recursive_dict(v, preserve_unicode) for k, v in obj.items()}
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 76, in <dictcomp>
    return {recursive_dict(k, preserve_unicode): recursive_dict(v, preserve_unicode) for k, v in obj.items()}
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 79, in recursive_dict
    return [recursive_dict(v, preserve_unicode) for v in obj]
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/utilities/fw_serializers.py", line 70, in recursive_dict
    return recursive_dict(obj.as_dict(), preserve_unicode)
  File "/lustre/home/umjzhh-1/kl_me2/codes/custodian/custodian/vasp/jobs.py", line 347, in as_dict
    default_vasp_input_set=self.default_vis.as_dict(),
AttributeError: 'dict' object has no attribute 'as_dict'
```

**Comment by computron** [comment]
As the error message shows, the last line of the error is in custodian. This means that the error has something to do with your workflow and is not some internal FireWorks error. Please fix your workflow, or provide evidence that there is a problem in FireWorks itself. Note that FireWorks does not help users debug their workflows. You might try https://groups.google.com/forum/#!forum/matproj-develop

For this time only, I will give you a hint, which si to make sure that things are serialized and de-serialized correctly. My guess is that self.default_vis is being loaded as a dictionary representation of VaspInputSet rather than a VaspInputSet *object*. But again, such questions are not covered in the FireWorks list - in the future, I will simply note that the question is off topic and close the thread.

**Comment by specter119** [comment]
Thank you.
