### ISSUE TITLE
pymongo 3.7.0 authentication problem

### ISSUE THREAD

**Issue by montoyjh** [materialsproject/fireworks#299]
I can post this on the google group too, but it seems like an internal bug so I'm posting it here for now.

Upgrading to pymongo 3.7.0 seems to cause authentication errors when the ping process tries to update the launch.  This can be remedied by downgrading to 3.6.1 (or perhaps later 3.6.x versions, haven't rigorously checked), we might want to pin the pymongo version until we get it sorted out.

**Comment by computron** [comment]
Thanks! Any hints on what might be the problem?

**Comment by computron** [comment]
@ardunn can you look into this?

I believe you can test it by updating pymongo to 3.7, running the unit tests, and seeing what fails ...

It's important we fix this sooner rather than later so as not to get too out of sync with the latest MongoDB

**Comment by ardunn** [comment]
@montoyjh Could you provide the stack trace? Running the current code with pymongo 3.7.0 + MongoDB 3.7.3 did not fail any tests (on either CircleCI or my machine).

What version of MongoDB are you using?

**Comment by computron** [comment]
Note that I am pretty sure at least CircleCI failed before - we reverted the commit to update pymongo because of the failure

I looked up the test and now the offending commit (which previously listed as failed) says it succeeded, and there is a note that says:

```
There was an issue while running this container and it was rerun. The most recent run is shown.
```

So if it was just CircleCI that was failing, it might have been some issue on their end?

**Comment by montoyjh** [comment]
Mongo version (on NERSC's mongodb03) is 3.2.16.  Here's a traceback:
```
Traceback (most recent call last):
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/rocket.py", line 243, in run
    Rocket.update_checkpoint(lp, launch_id, checkpoint)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/rocket.py", line 431, in update_checkpoint
    launchpad.ping_launch(launch_id, checkpoint=checkpoint)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/launchpad.py", line 1272, in ping_launch
    m_launch = self.get_launch_by_id(launch_id)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/launchpad.py", line 389, in get_launch_by_id
    m_launch = self.launches.find_one({'launch_id': launch_id})
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/collection.py", line 1262, in find_one
    for result in cursor.limit(-1):
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/cursor.py", line 1104, in _refresh
    self.__send_message(q)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/cursor.py", line 931, in __send_message
    operation, exhaust=self.__exhaust, address=self.__address)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1145, in _send_message_with_response
    exhaust)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1156, in _reset_on_error
    return func(*args, **kwargs)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/server.py", line 85, in send_message_with_response
    with self.get_socket(all_credentials, exhaust) as sock_info:
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/pool.py", line 1006, in get_socket
    sock_info.check_auth(all_credentials)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/pool.py", line 677, in check_auth
    auth.authenticate(credentials, self)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/auth.py", line 542, in authenticate
    auth_func(credentials, sock_info)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/auth.py", line 519, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/auth.py", line 279, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
Traceback (most recent call last):
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/rocket.py", line 243, in run
    Rocket.update_checkpoint(lp, launch_id, checkpoint)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/rocket.py", line 431, in update_checkpoint
    launchpad.ping_launch(launch_id, checkpoint=checkpoint)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/launchpad.py", line 1272, in ping_launch
    m_launch = self.get_launch_by_id(launch_id)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/launchpad.py", line 389, in get_launch_by_id
    m_launch = self.launches.find_one({'launch_id': launch_id})
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/collection.py", line 1262, in find_one
    for result in cursor.limit(-1):
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/cursor.py", line 1104, in _refresh
    self.__send_message(q)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/cursor.py", line 931, in __send_message
    operation, exhaust=self.__exhaust, address=self.__address)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1145, in _send_message_with_response
    exhaust)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1156, in _reset_on_error
    return func(*args, **kwargs)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/server.py", line 85, in send_message_with_response
    with self.get_socket(all_credentials, exhaust) as sock_info:
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/pool.py", line 1006, in get_socket
    sock_info.check_auth(all_credentials)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/pool.py", line 677, in check_auth
    auth.authenticate(credentials, self)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/auth.py", line 542, in authenticate
    auth_func(credentials, sock_info)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/auth.py", line 519, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/auth.py", line 279, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/m/montoyjh/cori-envs/builder/bin/rlaunch", line 11, in <module>
    sys.exit(rlaunch())
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/scripts/rlaunch_run.py", line 155, in rlaunch
    launch_rocket(launchpad, fworker, args.fw_id, args.loglvl, pdb_on_exception=args.pdb)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/rocket_launcher.py", line 58, in launch_rocket
    rocket_ran = rocket.run(pdb_on_exception=pdb_on_exception)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/rocket.py", line 383, in run
    lp.restore_backup_data(launch_id, m_fw.fw_id)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/fireworks/core/launchpad.py", line 1230, in restore_backup_data
    self.launches.find_one_and_replace({'launch_id': launch_id}, self.backup_launch_data[launch_id])
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/collection.py", line 3009, in find_one_and_replace
    session=session, **kwargs)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/collection.py", line 2872, in __find_and_modify
    write_concern.acknowledged, _find_and_modify, session)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1243, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1186, in _retry_with_session
    with self._get_socket(server) as sock_info:
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1058, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/pool.py", line 1006, in get_socket
    sock_info.check_auth(all_credentials)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/pool.py", line 677, in check_auth
    auth.authenticate(credentials, self)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/auth.py", line 542, in authenticate
    auth_func(credentials, sock_info)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/auth.py", line 519, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/auth.py", line 279, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/global/homes/m/montoyjh/cori-envs/builder/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
```

**Comment by ardunn** [comment]
@montoyjh are you authenticating in a way that is not run in the tests?

Otherwise I'm not sure why the tests would pass but you'd still have issues, unless the difference in MongoDB versions is the problem (unlikely but possible)...

**Comment by computron** [comment]
You should check mongodb version

**Comment by ardunn** [comment]
Using pymongo 3.7.0 with mongo 3.2.16 passes all tests.

**Comment by dwinston** [comment]
I discovered that, with pymongo 3.7, I could not re-use a `MongoClient` instance after `close()`ing it, whereas I can do this with 3.6.1 (and earlier). It seems that earlier versions retain the authentication info, but 3.7 dropped this functionality. I think this is a bug, so I filed a [ticket](https://jira.mongodb.org/browse/PYTHON-1613) with MongoDB. Perhaps this was the issue encountered.

**Comment by dwinston** [comment]
[pymongo 3.7.1](https://api.mongodb.com/python/3.7.1/changelog.html) has been released and might fix the issue. @montoyjh can you re-try with 3.7.1? I suggest closing this issue and re-opening if 3.7.1 does not resolve the problem.

**Comment by computron** [comment]
I haven't heard any chatter for awhile so I am closing this issue, please re-open if this is still a problem

**Comment by Error1996** [comment]
i am still having this error after uninstalling pymongo 3.7 and installing pymongo 3.6.1
please help!!!
