### ISSUE TITLE
bulk_add_wfs does not work

### ISSUE THREAD

**Issue by boehms** [materialsproject/fireworks#395]
Adding list of Fireworks creates and error:
Workflow.from_firework(wf) is mistyped; should be Workflow.from_Firework(wf).

Using workflows it hangs in Pymongo.

**Comment by mkhorton** [comment]
You should be adding a list of workflows, not a list of fireworks. `bulk_add_wfs` does work, I used it myself yesterday :)

If you have further issues, an example and your OS, Python, package versions would be needed so we can reproduce the issue.

**Comment by boehms** [comment]
OS is el7a.ppc64le
Python is 3.8
Fireworks is 1.9.5

Using the following code

'''wfs = []

for x in range(1, 100):

    fw = Firework(tasks=[], spec=conf['spec'])
    #wf = Workflow([fw])
    wfs.append(fw)
    #wfs.append(wf)

    # store workflow and launch it locally, single shot
    #launchpad.add_wf(fw)
    #launch_rocket(launchpad, FWorker())

launchpad.bulk_add_wfs(wfs)
'''

I get the following error:
'''
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:00<00:00, 41565.17it/s]
Traceback (most recent call last):
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/pool.py", line 643, in receive_message
    return receive_message(self.sock, request_id,
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/network.py", line 196, in receive_message
    _receive_data_on_socket(sock, 16))
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/network.py", line 255, in _receive_data_on_socket
    chunk_length = sock.recv_into(mv[bytes_read:])
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docking_launcher.py", line 49, in <module>
    launchpad.bulk_add_wfs(wfs)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/fireworks/core/launchpad.py", line 448, in bulk_add_wfs
    self.workflows.insert_many(wf.to_db_dict() for wf in wfs)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/collection.py", line 758, in insert_many
    blk.execute(write_concern, session=session)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/bulk.py", line 511, in execute
    return self.execute_command(generator, write_concern, session)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/bulk.py", line 345, in execute_command
    client._retry_with_session(
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/bulk.py", line 339, in retryable_bulk
    self._execute_command(
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/bulk.py", line 295, in _execute_command
    result, to_send = bwc.execute(ops, client)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/message.py", line 899, in execute
    result = self.write_command(request_id, msg, to_send)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/message.py", line 988, in write_command
    reply = self.sock_info.write_command(request_id, msg)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/pool.py", line 686, in write_command
    reply = self.receive_message(request_id)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/pool.py", line 646, in receive_message
    self._raise_connection_failure(error)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/pool.py", line 795, in _raise_connection_failure
    _raise_connection_failure(self.address, error)
  File "/sw/summit/fireworks/1.9.5/python/lib/python3.8/site-packages/pymongo/pool.py", line 281, in _raise_connection_failure
    raise NetworkTimeout(msg)
pymongo.errors.NetworkTimeout: stf010.marble.ccs.ornl.gov:30094: timed out
/sw/summit/fireworks/1.9.5/python/bin/python3 docking_launcher.py  0.24s user 0.08s system 0% cpu 5:00.83 total
'''

Note, I changed Workflow.from_firework(wf) to Workflow.from_Firework(wf) in https://github.com/materialsproject/fireworks/blob/e33821518acf4dc7276aa161a523a0770a776191/fireworks/core/launchpad.py#L424

I see the same error if I create the workflow (commented out in above snippet.

**Comment by mkhorton** [comment]
This code:

```
wfs = []

for x in range(1, 100):

    fw = Firework(tasks=[], spec=conf['spec'])
    #wf = Workflow([fw])
    wfs.append(fw)
    #wfs.append(wf)

    # store workflow and launch it locally, single shot
    #launchpad.add_wf(fw)
    #launch_rocket(launchpad, FWorker())

launchpad.bulk_add_wfs(wfs)
```

should read:

```
wfs = []

for x in range(1, 100):

    fw = Firework(tasks=[], spec=conf['spec'])
    wf = Workflow([fw])
    wfs.append(wf)

launchpad.bulk_add_wfs(wfs)
```

**Comment by boehms** [comment]
As mentioned, I get the same error using either variant.

This code snippet works fine:
```
for x in range(1, 100):

    fw = Firework.from_dict(conf)

    launchpad.add_wf(fw)
```

Using this code I get the error mentioned earlier:
```
for x in range(1, 100):

    fw = Firework.from_dict(conf)
    wf = Workflow.from_Firework(fw)
    wfs.append(wf)

launchpad.bulk_add_wf(wfs)
```

**Comment by mkhorton** [comment]
Perhaps it's an issue with your database being under-provisioned, since the error quoted is:

`pymongo.errors.NetworkTimeout: stf010.marble.ccs.ornl.gov:30094: timed out`

**Comment by boehms** [comment]
That is a possibility I can investigate. It seems like I can add up to 4 workflows at a time. Everything else times out.
