### ISSUE TITLE
Fireworks (1.9.5 later) can not be installed on Windows 10

### ISSUE THREAD

**Issue by goodwilling** [materialsproject/fireworks#417]
Hi. Fireworks works great in Linux. 
However, using the same command in miniconda3 environment of Windows 10 Pro (locale: shift-JIS):

pip install fireworks

the error comes out as:
------------------
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\test\AppData\Local\Temp\pip-install-bqrhom7v\fireworks\setup.py", line 22, in <module>
        long_description=open(os.path.join(module_dir, 'README.md')).read(),
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x93 in position 817: illegal multibyte sequence
------------------

On the other hand, no error occurs if a version <= 1.9.4 is specified:  

pip  install  fireworks==1.9.4

Thank you very much.

**Comment by devthepenguin** [comment]
Hey, I am able to install Fireworks successfully on Windows 10.

**Option 1- Install Fireworks with conda**

```conda install -c matsci fireworks```

**Option 2- Install Fireworks in development mode:**

```git clone https://github.com/materialsproject/fireworks.git```

followed by

```python setup.py install```

This should resolve installation error.

**Comment by arosen93** [comment]
I can confirm this is no longer an issue.
